name: Sync to Xposed-Modules-Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to target repo
        run: |
          git remote add target https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/Xposed-Modules-Repo/io.mo.glassmic.git
          git push target main --force
